### ISSUE TITLE
List of exemplary editions

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/Institute-Materials-2020#15]
As discussed in the 2022-06-01 Zoom conversation with @bleekere, @EmmaSchwarz, and @djbpitt:

@bleekere will copy the list of exemplary editions from our 2017 Institute into the new one and update it. Elli will also take the lead in preparing our presentation and discussion of selected exemplary editions in the Institute.

**Comment by bleekere** [comment]
See #18

**Comment by djbpitt** [comment]
Thanks, @bleekere . I've merged your commit into the gh-pages branch. I added Jeffrey Witt's Petrus Plaoul site under large corpora because Jeffrey is one of our guest lecturers and he'll introduce the site then. You may remember him from the Graz DiXiT workshop.
