### ISSUE TITLE
Arrange Reception 

### ISSUE THREAD

**Issue by EmmaSchwarz** [Pittsburgh-NEH-Institute/Institute-Materials-2020#16]

**Comment by gabikeane** [comment]
remaining tasks
-[ ] send final quote including tables
-[x] send invitations to non-participants
-[x] ask Taylor about tax exemption

**Comment by djbpitt** [comment]
* Invitations sent to non-participants 2022-07-02, as well as to guest lecturers who might be in town that day
* Request for tax-exemption letter sent to Taylor 2022-07-01.
* Waiting for final reception contract from Marchaé (including tables; we have Samantha’s catering contract) to send to sponsors.

**Comment by djbpitt** [comment]
Done!
