### ISSUE TITLE
04-index documentation has incorrect paths

### ISSUE THREAD

**Issue by wraabe** [Pittsburgh-NEH-Institute/Institute-Materials-2020#23]
For 04-index, the paths in code examples do not match current iteration.
Current 01_document_by_first_letter.xql and 02_simple_xml.xql
```
declare variable $stories as document-node()+ := 
	collection('/db/apps/neh_04_http/xml');
```
Should be: 

```
declare variable $stories as document-node()+ := 
	collection('/db/apps/04-index/data/hoax_xml');
```

**Comment by djbpitt** [comment]
Thank you, @wraabe. I may be looking in the wrong place, but I don't see _01_document_by_first_letter.xql_ or _02_simple_xml.xql_ in the [04-index repo](https://github.com/Pittsburgh-NEH-Institute/04-index). Would you be able to provide URLs to the GitHub locations of the problem files?

**Comment by wraabe** [comment]
See sample code in this file:
[https://github.com/Pittsburgh-NEH-Institute/Institute-Materials-2020/blob/gh-pages/eXist-db-stages/neh_04_http.md](https://github.com/Pittsburgh-NEH-Institute/Institute-Materials-2020/blob/gh-pages/eXist-db-stages/neh_04_http.md)

Names referenced (proposed for users to create) are as follows:
_01_document_by_first_letter.xql_

Below is code example:

```
xquery version "3.1";
declare namespace tei="http://www.tei-c.org/ns/1.0";
declare variable $stories as document-node()+ := 
	collection('/db/apps/neh_04_http/xml'); (: <!-- See this line :) 
declare variable $initial as xs:string := 
	request:get-parameter('initial', 'A');
declare variable $hits as document-node()* := 
    $stories[descendant::tei:titleStmt/tei:title[starts-with(., $initial)]];
$hits/descendant::tei:titleStmt/tei:title ! string()
```

**Comment by wraabe** [comment]
I think code sample appears only once.

**Comment by djbpitt** [comment]
@wraabe Oops! That entire directory predates this year's (!) Institute preparation. The stages we really use are directly under https://github.com/orgs/Pittsburgh-NEH-Institute/repositories. Meanwhile, I've created a *deprecated* directory in the repo and moved the entire *eXist-db-stages* subtree under it. Apologies for not having cleaned this up earlier!
