### ISSUE TITLE
Interactive XQuery development resources

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/Institute-Materials-2020#4]
In addition to Joe’s Jupyter integration, see Martin Honnen’s <http://xqueryfiddle.liberty-development.net/>. For comparison, see Mike Bostock’s <https://observablehq.com/>.

**Comment by djbpitt** [comment]
This is still relevant. @djbpitt to add to resources links.

**Comment by line-o** [comment]
@djbpitt Hi! I am also looking into ways to get to an eXist-db XQuery playground. I am a frequent user of both websites you referenced in addition to [jsbin](https://jsbin.com/?html,output) et al. I would be glad to hear your thoughts on this and share mine, if you are interested. (@joewiz pointed me at this issue)

**Comment by djbpitt** [comment]
For Institute purposes, used local eXist-db installations instead of online fiddle/playground.
