### ISSUE TITLE
Update ref/setup.md with fuller installation/update directions

### ISSUE THREAD

**Issue by joewiz** [Pittsburgh-NEH-Institute/Institute-Materials-2020#5]
Update https://github.com/Pittsburgh-NEH-Institute/Institute-Materials-2020/blob/gh-pages/ref/setup.md with:
- how to install homebrew for mac users and use it to install java, eXist, oXygen (and account for possibility people have installed some of these via other routes) 
- latest recommendations for installing Java and eXist Windows users - see TEI Publisher 5.0.2 quick start documentation
- how to backup/restore from eXist 4.x in preparation for upgrade to eXist 5

**Comment by djbpitt** [comment]
This is still relevant; we should revisit our installation guide.

**Comment by gabikeane** [comment]
@EmmaSchwarz has added an installation.md tutorial
