### ISSUE TITLE
Create Jupyter support app for eXist-db

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/Institute-Materials-2020#6]
@joewiz Peel off Atom-support as separate Jupyter support app

**Comment by joewiz** [comment]
- limit the jupyter-support app to query execution
- add response headers with content-type of result
- add try/catch to return relevant status codes for jupyter users (distinguish between serialization errors, which currently raise a 400 error and return an `<exception>` element, and syntax errors, which currently raise a 500 error and return as HTML)
- when added, enhance the jupyter run_xquery function to read the content-type, apply the appropriate syntax highlighting, and handle error codes/contents

**Comment by djbpitt** [comment]
Once the new Jupyter support app is in place, @djbpitt to enhance Python module as package for pip installation

**Comment by joewiz** [comment]
Actually, since items in the response may be of different content types, we'll return content-type hints for each item. The jupyter end will apply the correct syntax highlighting to each item in the response.

**Comment by djbpitt** [comment]
Not using Jupyter in this Institute; using eXide instead.
