### ISSUE TITLE
Investigate installation methods that avoid Java dependency problems for Windows users

### ISSUE THREAD

**Issue by joewiz** [Pittsburgh-NEH-Institute/Institute-Materials-2020#7]
... to relieve users of the need to (re-/un-) install java

**Comment by joewiz** [comment]
This was discussed at yesterday's eXist Community Call; see p. 4 of the call notes, https://docs.google.com/document/d/1OiyEDGly_qbriRZOdr9wveF82sgb6yQt7VdXLjH-SAc/edit?usp=sharing. 

While a Java-embedded distribution of eXist isn't out of the question, the most promising and shortest path to a solution seems to be to create a chocolatey package for eXist, which can declare a dependency on a JDK/JRE. I've now got chocolatey installed on a Windows 10 VM and will see if I can make progress on this. 

The chocolatey community allows people to submit a "request for package" (RFP), which I've just done, in the hope that a chocolatey-savvy user is willing to help develop a package: https://github.com/chocolatey-community/chocolatey-package-requests/issues/760.

**Comment by djbpitt** [comment]
At the moment none of us has the bandwidth to develop a Chocolatey package proposal, but, as @joewiz writes, we now know how to pursue that course of action should we need to do it in the future. For Institute purposes we will use an existing method to install eXist-db under Windows.
